apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secrets
type: Opaque
data:
  connection_string: "Server=svr-db-pokezon-customer.database.windows.net;Database=CustomerContext;User=customerad;Password=PasswordO1."
  