// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokezon.CustomerApi.Data.Database;

namespace Pokezon.CustomerApi.Data.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokezon.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokeCollection")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f35b48d-cb87-4783-bfdb-21e36012930a"),
                            Age = 30,
                            Birthday = new DateTime(1989, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wolfgang",
                            LastName = "Ofner",
                            PokeCollection = 0,
                            Total = 60
                        },
                        new
                        {
                            Id = new Guid("654b7573-9501-436a-ad36-94c5696ac28f"),
                            Age = 43,
                            Birthday = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Darth",
                            LastName = "Vader",
                            PokeCollection = 0,
                            Total = 6
                        },
                        new
                        {
                            Id = new Guid("971316e1-4966-4426-b1ea-a36c9dde1066"),
                            Age = 83,
                            Birthday = new DateTime(1937, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Son",
                            LastName = "Goku",
                            PokeCollection = 0,
                            Total = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
